pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "jrishi904/jenkins-demo"
    }

    stages {

        stage('Build App') {
            agent {
                docker {
                    image 'node:18'
                }
            }
            steps {
                dir('app'){
                sh 'npm install'
                sh 'npm run build'
                }    
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE -f docker/Dockerfile .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }
    }
}
