stages {

    stage('Build App') { ... }

    stage('Build Docker Image') {
        steps {
            sh 'docker build -t jrishi904/jenkins-demo -f docker/Dockerfile .'
        }
    }

    stage('Docker Login') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )]) {
                sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
            }
        }
    }

    stage('Push Docker Image') {
        steps {
            sh 'docker push jrishi904/jenkins-demo'
        }
    }
}
